# Generated by Django 3.2.9 on 2021-12-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
